const Options = [{ key: 0, text: "age", value: "age" },
{ key: 1, text: "class of worker", value: "class of worker" },
{ key: 2, text: "industry code", value: "industry code" },
{ key: 3, text: "occupation code", value: "occupation code" },
{ key: 4, text: "education", value: "education" },
{ key: 5, text: "wage per hour", value: "wage per hour" },
{ key: 6, text: "last education", value: "last education" },
{ key: 7, text: "marital status", value: "marital status" },
{ key: 8, text: "major industry code", value: "major industry code" },
{ key: 9, text: "major occupation code", value: "major occupation code" },
{ key: 10, text: "mace", value: "mace" },
{ key: 11, text: "hispanice", value: "hispanice" },
{ key: 12, text: "sex", value: "sex" },
{ key: 13, text: "member of labor", value: "member of labor" },
{ key: 14, text: "reason for unemployment", value: "reason for unemployment" },
{ key: 15, text: "fulltime", value: "fulltime" },
{ key: 16, text: "capital gain", value: "capital gain" },
{ key: 17, text: "capital loss", value: "capital loss" },
{ key: 18, text: "dividends", value: "dividends" },
{ key: 19, text: "income tax liability", value: "income tax liability" },
{ key: 20, text: "previous residence region", value: "previous residence region" },
{ key: 21, text: "previous residence state", value: "previous residence state" },
{ key: 22, text: "household-with-family", value: "household-with-family" },
{ key: 23, text: "household-simple", value: "household-simple" },
{ key: 24, text: "weight", value: "weight" },
{ key: 25, text: "msa-change", value: "msa-change" },
{ key: 26, text: "reg-change", value: "reg-change" },
{ key: 27, text: "within-reg-change", value: "within-reg-change" },
{ key: 28, text: "lived-here", value: "lived-here" },
{ key: 29, text: "migration prev res in sunbelt", value: "migration prev res in sunbelt" },
{ key: 30, text: "num persons worked for employer", value: "num persons worked for employer" },
{ key: 31, text: "family members under 118", value: "family members under 118" },
{ key: 32, text: "father birth country", value: "father birth country" },
{ key: 33, text: "mother birth country", value: "mother birth country" },
{ key: 34, text: "birth country", value: "birth country" },
{ key: 35, text: "citizenship", value: "citizenship" },
{ key: 36, text: "own business or self employed", value: "own business or self employed" },
{ key: 37, text: "fill questionnaire for veteran's admin", value: "fill questionnaire for veteran's admin" },
{ key: 38, text: "veterans benefits", value: "veterans benefits" },
{ key: 39, text: "weeks worked in year", value: "weeks worked in year" },
{ key: 40, text: "year", value: "year" },
{ key: 41, text: "salary range", value: "salary range" }];

export default Options;